### ISSUE TITLE
 LorentzVectors from PT, Eta, Phi, Energy,

### ISSUE THREAD

**Issue by MTerwissen** [JuliaHEP/LorentzVectorHEP.jl#2]
Hi @Moelf,

Thanks for the great package!
We would like to have a function  for creating LorentzVectors from PT, Eta, Phi, Energy, i.e., something like:
```
function LorentzVectorCylE(pt, eta, phi, E)
    m2 = E^2 - pt^2 - (sinh(eta) * pt)^2
    m = sign(m2) * sqrt(abs(m2)) 
    return LorentzVectorCyl(pt, eta, phi, m) 
  end
  ```
(Similar to ROOT's [SetPTEtaPhiE](https://root.cern.ch/doc/master/classTLorentzVector.html#a6f5009aa2696a4e54eed4b29834ca3f0) method)
I don't know if this is the best way to do it or if it would make sense to have more general functions for converting energies and masses, for example to use it both for cartesian and cylindrical LorentzVectors.

**Comment by Moelf** [comment]
Would accept the PR gladly

**Comment by Moelf** [comment]
Maybe make the function name `fromPtEtaPhiE`

So it doesn't implicitly return a type that's not the name of the function while the function looks like a constructor

**Comment by Moelf** [comment]
closed by https://github.com/JuliaHEP/LorentzVectorHEP.jl/pull/3
